#spring:
#  security:
#    user:
#      name: devhp
#      password: password123


server:
  port: 8888
  servlet:
    context-path: /devhp
    
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

