server:
  port: 9999
  servlet:
    context-path: /devhp
    
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': false
    hibernate:
      ddl-auto: update        # Không nên dùng cấu hình này trong môi trường PRD.
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://alpha.india.mkdb.sh:5432/gczxlfjc
    username: stqzffyn
    password: ffyfmajfmafrgwptxsxq



#  psql postgresql://stqzffyn:ffyfmajfmafrgwptxsxq@alpha.india.mkdb.sh:5432/gczxlfjc